# Generated by Django 4.2.2 on 2023-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Convener', 'Convener'), ('Head of Coorporate communication', 'Head of Coorporate communication'), ('Head of Operations', 'Head of Operations'), ('Technical Head', 'Technical Head'), ('Baja Coordinator', 'Baja Coordinator'), ('Creative Head', 'Creative Head'), ('Publicity Head', 'Publicity Head'), ('Webd Head', 'Webd Head'), ('Head Ath', 'Head Ath'), ('Event Head', 'Event Head'), ('WorkShop Head', 'WorkShop Head')], max_length=100),
        ),
    ]
